#!/bin/bash
set -euo pipefail

ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

if [ -f "$ENV_FILE" ]; then
    echo ".env already exists at $ENV_FILE, not overwriting." >&2
    exit 0
fi

DB_ROOT_PW=$(openssl rand -base64 24)
NT_DB_PW=$(openssl rand -base64 24)
NT_ROOT_PW=$(openssl rand -base64 24)

cat > "$ENV_FILE" <<EOF
# Generated by docker/generate-env.sh

# --- Database (MariaDB) ---
DB_ROOT_PASSWORD=$DB_ROOT_PW
NICTOOL_DB_NAME=nictool
NICTOOL_DB_USER=nictool
NICTOOL_DB_USER_PASSWORD=$NT_DB_PW

# --- Legacy NicTool v2 ---
ROOT_USER_EMAIL=admin@example.com
ROOT_USER_PASSWORD=$NT_ROOT_PW

# --- Port mapping (optional) ---
# DB_PORT=3307
# API_PORT=3000
# SERVER_PORT=8080
# LEGACY_HTTP_PORT=8082
# LEGACY_HTTPS_PORT=8443
EOF

echo "Generated $ENV_FILE with random passwords."
